# Generated by Django 3.0.3 on 2020-07-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companypost',
            old_name='author',
            new_name='user',
        ),
    ]
