# Generated by Django 3.0.3 on 2020-07-28 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200727_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='identifier',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
