# Generated by Django 3.0.3 on 2020-07-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_application_identifier'),
        ('posts', '0006_auto_20200728_1322'),
    ]

    operations = [
    ]
