# Generated by Django 3.0.6 on 2020-07-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_companypost_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypost',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
