# Generated by Django 3.0.3 on 2020-07-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200730_1415'),
        ('posts', '0010_auto_20200730_1926'),
    ]

    operations = [
    ]
