# Generated by Django 3.0.3 on 2020-08-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200813_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypost',
            name='city',
            field=models.CharField(default='Bucuresti', max_length=50),
            preserve_default=False,
        ),
    ]
