# Generated by Django 3.0.3 on 2020-08-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_companypost_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypost',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
