# Generated by Django 3.0.6 on 2020-07-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='document',
            field=models.FileField(blank=True, max_length=255, upload_to='media'),
        ),
    ]
