# Generated by Django 3.0.3 on 2020-07-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_telephone',
            new_name='telephone',
        ),
    ]
