# Generated by Django 3.0.3 on 2020-07-27 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200724_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cv',
            field=models.FileField(default=django.utils.timezone.now, upload_to='CVs'),
            preserve_default=False,
        ),
    ]
