# Generated by Django 3.0.3 on 2020-07-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200724_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(default='user.png', upload_to='profile_pics'),
        ),
    ]
