# Generated by Django 3.0.3 on 2020-07-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200724_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.TextField(default='Tell us something about you', max_length=1000),
        ),
    ]
